import { Paytone_One, Baloo_Da_2, Caveat } from "next/font/google";
import "../globals.css";
import Sidenav from "@/components/Sidenav";

const paytone = Paytone_One({
  variable: "--font-paytone",
  weight: "400",
});

const baloo = Baloo_Da_2({
  variable: "--font-baloo",
  weight: ["400", "500", "600", "700", "800"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Reisleiders",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-white">
      <body
        className={`${paytone.variable} ${baloo.variable} ${caveat.variable} antialiased h-full`}
      >
        <Sidenav>{children}</Sidenav>
      </body>
    </html>
  );
}
