import {
  Paytone_One,
  Baloo_Da_2,
  Caveat,
  Caveat_Brush,
} from "next/font/google"; // Importeer Google Fonts via Next.js
import "../globals.css"; // Globale CSS voor het hele project
import Sidenav from "@/components/Sidenav"; // Import van je zijbalk component

// Fonts instellen met variabelen voor gebruik in CSS
const paytone = Paytone_One({
  variable: "--font-paytone",
  weight: "400",
});

const baloo = Baloo_Da_2({
  variable: "--font-baloo",
  weight: ["400", "500", "600", "700", "800"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  weight: ["400", "500", "600", "700"],
});

const caveatBrush = Caveat_Brush({
  variable: "--font-caveat-brush",
  weight: "400",
});

// Metadata voor de pagina (titel en omschrijving)
export const metadata = {
  title: "Reisleiders",
  description: "Generated by create next app",
};

// Hoofdlayout component
export default function MainLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-white">
      <body
        className={`${paytone.variable} ${baloo.variable} ${caveat.variable} ${caveatBrush.variable} antialiased h-full`}
      >
        {/* Sidenav component omsluit de hele inhoud */}
        <Sidenav>{children}</Sidenav>
      </body>
    </html>
  );
}
